import Foundation

extension Strings {
    public static let en = Strings(
        brandTagline: "Local AI markdown editor",
        common: Common(
            back: "Back", cancel: "Cancel", delete: "Delete", change: "Change", justNow: "just now"),
        ob: Onboarding(
            langTitle: "Welcome to Sage",
            langSub: "Your private AI note editor. Choose a language.",
            stepFolder: "Step 2 of 5",
            folderTitle: "Where are your notes?",
            folderSub: "Pick a folder with .md files. Sage works right inside it — like Obsidian.",
            chooseFolder: "Choose folder",
            folderHint: "Any folder with Markdown files",
            folderPicked: "Folder selected",
            privacyNote: "Your notes stay on your Mac. Sage sends nothing to the cloud.",
            stepModel: "Step 3 of 5",
            modelTitle: "Pick an AI model",
            modelSub: "The model downloads and runs locally. Change it anytime.",
            recommended: "Recommended",
            stepWhisper: "Step 4 of 5",
            whisperTitle: "Speech-to-text",
            whisperSub: "Pick a Whisper model for voice input — it also runs locally. You can skip this.",
            stepDownload: "Step 5 of 5",
            downloading: "Downloading model…",
            verifying: "Verifying integrity…",
            dlDone: "Model is ready",
            dlErrorMsg: "Could not download the model. Check your connection and try again.",
            retry: "Retry download",
            readyTitle: "All set!",
            readySub: "Sage is configured and runs fully offline. Enjoy.",
            continueAction: "Continue",
            openSage: "Open Sage",
            stageModel: "Step 1 of 2 · answer model",
            stageWhisper: "Step 2 of 2 · speech recognition (Whisper)",
            stageOnlyModel: "answer model only",
            downloadContinue: "Download and continue",
            speedUnit: "MB/s"
        ),
        nav: Nav(search: "Search", editor: "Editor", chat: "Chat with Sage"),
        app: App(
            files: "Files", localRunning: "running locally",
            outline: "Outline", info: "Info", words: "Words", edited: "Edited",
            askInline: "Ask Sage about this text",
            aiThinking: "Sage is thinking…", aiImproving: "Sage is improving the text…",
            aiContinuing: "Sage is continuing…", aiSummarizing: "Sage is summarizing…",
            aiApplied: "Applied", aiFailed: "No response from the model",
            newNote: "New note",
            openFolder: "Open folder",
            emptyVaultTitle: "No notes yet",
            emptyVaultBody: "There are no .md files in this folder. Create your first note or open another folder with notes.",
            newNoteName: "Note",
            noSelectionTitle: "No note selected",
            noSelectionBody: "Pick a note from the list on the left, or create a new one.",
            newFolder: "New folder",
            rename: "Rename",
            open: "Open",
            deleteFolder: "Delete folder",
            sortBy: "Sort", sortByName: "By name", sortByModified: "By date modified",
            copyPath: "Copy path", copied: "Copied",
            ready: "ready"
        ),
        chat: Chat(
            title: "Chat with Sage",
            placeholder: "Ask anything about your notes…",
            perm: "Requesting microphone access…",
            transcribing: "Transcribing speech…",
            errorMsg: "Could not get a response from the model. It may be out of memory.",
            retry: "Retry",
            stopGen: "Stop",
            voiceTitle: "Listening…",
            voiceHint: "Speak — Whisper transcribes locally",
            voiceCancel: "cancel",
            voiceConfirm: "stop & transcribe",
            history: "History",
            historyHeader: "Chat history · linked to files and folders",
            ctxVault: "Whole vault",
            ctxSelection: "Selected text",
            clearChat: "Clear chat",
            deletePrompt: "Delete this note?",
            deleted: "Moved to Trash",
            askTitle: "Ask Sage",
            askBody: "Answers from your notes — fully offline. The context can be a file or a whole folder.",
            copy: "Copy",
            suggest1: "Briefly, what is this about",
            suggest2: "Highlight the key points",
            suggest3: "Ask questions about the content",
            histToday: "Today", histYesterday: "Yesterday", histEarlier: "Earlier",
            histEmptyTitle: "No history yet",
            histEmptyBody: "Conversations with Sage are saved here and linked to the file or folder you asked about."
        ),
        search: Search(
            placeholder: "Search all notes…",
            noResults: "No results",
            askSub: "Ask the local AI across all notes",
            searching: "Searching…",
            recent: "Recent",
            results: "Results",
            askPrefix: "Ask Sage"
        ),
        settings: Settings(
            title: "Settings", general: "General", ai: "AI Model", appearance: "Appearance",
            git: "Git Sync", about: "About",
            generalSub: "Language, vault and app behaviour",
            language: "Interface language", languageSub: "Русский, English or 中文",
            vault: "Notes folder", change: "Change",
            startup: "Launch at login", startupSub: "Open Sage on macOS startup",
            spellcheck: "Spell check", spellcheckSub: "Underline mistakes in text",
            aiSub: "Manage local models and AI behaviour",
            llmSection: "Answer & summary model · LLM",
            whisperSection: "Speech recognition · Whisper", download: "Download",
            appearanceSub: "Theme and accent color",
            theme: "Theme", accent: "Accent color", accentSub: "Highlight and button color",
            gitSub: "Sync notes via a Git repository",
            gitConnectTitle: "Connect Git",
            gitConnectSub: "Version and sync your notes via GitHub, GitLab or your own server.",
            gitConnect: "Connect repository",
            branch: "Branch", lastSync: "synced", synced: "Synced", disconnect: "Disconnect",
            gitTokenHint: "HTTPS token (Personal Access Token)",
            autoSync: "Auto-sync", autoSyncSub: "Commit and push changes automatically",
            syncFrequency: "Sync frequency",
            syncFrequencySub: "How often to push changes to the repository",
            freqOnChange: "On change", freqEvery5: "5 min", freqHourly: "Hour", freqManual: "Manual",
            recentCommits: "Recent commits", syncNow: "Sync now", syncing: "Syncing…",
            version: "Version",
            chipLocal: "100% local", chipSilicon: "Apple Silicon", chipMarkdown: "Markdown",
            updates: "Updates", updatesSub: "Sage updates automatically in the background",
            upToDate: "Up to date", checkingUpdates: "Checking for updates…", installingUpdate: "Installing…",
            checkUpdates: "Check for updates", checkNow: "Check now", lastChecked: "Last checked",
            updateAvailable: "New version", updateNow: "Update",
            downloadingUpdate: "Downloading", updateReady: "ready to install", restartNow: "Restart",
            updateFailed: "Couldn’t download the update", retryUpdate: "Retry",
            autoUpdate: "Auto-update", autoUpdateSub: "Download and install updates in the background",
            youHaveVersion: "you’re on",
            updateReadyTitle: "Update ready", updateAvailableTitle: "Update available", openAction: "Open",
            updateErrNetwork: "Couldn’t reach the update server",
            updateErrChecksum: "Checksum didn’t match",
            updateErrNoApp: "No app found in the archive",
            updateErrInstall: "Couldn’t install the update",
            downloadIncomplete: "Download didn’t complete"
        ),
        theme: Theme(dark: "Dark", light: "Light", auto: "Auto"),
        tray: Tray(
            statusRunning: "running locally", newChat: "New chat",
            search: "Search", settings: "Settings", quit: "Quit Sage"
        ),
        menu: Menu( edit: "Edit", goMenu: "Go", find: "Find…", toggleSidebar: "Toggle Sidebar",
            settings: "Settings…",
            editorView: "Editor", chatView: "Chat with Sage", settingsView: "Settings", cycleTheme: "Cycle Theme",
            aiMenu: "AI", askSage: "Ask Sage…"
        ),
        models: Models(
            descSmall: "Lightweight: fast on any Mac",
            descMid: "Smart, strong at code and multilingual",
            descLarge: "Top quality, needs a powerful Mac", ramSmall: "6 GB RAM", ramMid: "8 GB RAM", ramLarge: "16 GB RAM",
            whisperBaseDesc: "Best balance of speed and accuracy",
            whisperSmallDesc: "Higher accuracy, slower",
            whisperTinyDesc: "Fastest, basic accuracy",
            whisperTurboDesc: "High accuracy, accelerated",
            whisperNone: "No voice input",
            whisperNoneDesc: "You can enable it later in settings",
            notInstalled: "not downloaded", active: "active", installed: "downloaded",
            downloadingStatus: "Downloading…"
        ),
        slash: Slash(
            aiAsk: "Ask Sage…",
            linkURL: "Link (URL)", linkNote: "Note (.md)", linkText: "Text",
            linkAdd: "Add", linkCreate: "Create note",
            blkText: "Text", blkH1: "Heading 1", blkH2: "Heading 2", blkH3: "Heading 3",
            blkBullet: "Bulleted list", blkNumbered: "Numbered list", blkCheck: "To-do list",
            blkQuote: "Quote", blkTable: "Table", blkCode: "Code", blkDivider: "Divider",
            blkLink: "Link", tableColumn: "Column"),
        toast: Toast(
            folderOpened: "Folder opened",
            aiReplied: "Sage replied in"),
        git: Git(
            commitAutoSync: "auto-sync", commitMerge: "merge remote",
            syncUpToDate: "Up to date", syncPushed: "Pushed", syncConflict: "Conflict",
            syncNoRepo: "No repository", syncUnrelated: "Unrelated histories — reconnect the repository",
            connectConflict: "Merge conflict")
    )
}
