import Foundation

extension Strings {
    public static let ru = Strings(
        brandTagline: "Локальный ИИ-редактор заметок",
        common: Common(
            back: "Назад", cancel: "Отмена", delete: "Удалить", change: "Изменить", justNow: "только что"),
        ob: Onboarding(
            langTitle: "Добро пожаловать в Sage",
            langSub: "Ваш приватный ИИ-редактор заметок. Выберите язык.",
            stepFolder: "Шаг 2 из 5",
            folderTitle: "Где хранятся ваши заметки?",
            folderSub: "Выберите папку с .md файлами. Sage будет работать прямо с ними — как Obsidian.",
            chooseFolder: "Выбрать папку",
            folderHint: "Любая папка с Markdown-файлами",
            folderPicked: "Папка выбрана",
            privacyNote: "Заметки остаются на вашем Mac. Sage ничего не отправляет в облако.",
            stepModel: "Шаг 3 из 5",
            modelTitle: "Выберите ИИ-модель",
            modelSub: "Модель скачается и будет работать локально. Сменить можно в любой момент.",
            recommended: "Рекомендуем",
            stepWhisper: "Шаг 4 из 5",
            whisperTitle: "Распознавание речи",
            whisperSub: "Выберите модель Whisper для голосового ввода — она тоже работает локально. Можно пропустить.",
            stepDownload: "Шаг 5 из 5",
            downloading: "Скачивание модели…",
            verifying: "Проверка целостности…",
            dlDone: "Модель готова к работе",
            dlErrorMsg: "Не удалось загрузить модель. Проверьте подключение и попробуйте снова.",
            retry: "Повторить загрузку",
            readyTitle: "Всё готово!",
            readySub: "Sage настроен и работает полностью локально. Приятной работы.",
            continueAction: "Продолжить",
            openSage: "Открыть Sage",
            stageModel: "Этап 1 из 2 · модель ответов",
            stageWhisper: "Этап 2 из 2 · распознавание речи (Whisper)",
            stageOnlyModel: "только модель ответов",
            downloadContinue: "Скачать и продолжить",
            speedUnit: "МБ/с"
        ),
        nav: Nav(search: "Поиск", editor: "Редактор", chat: "Чат с Sage"),
        app: App(
            files: "Файлы", localRunning: "работает локально",
            outline: "Структура", info: "Информация", words: "Слов", edited: "Изменён",
            askInline: "Спросить Sage об этом тексте",
            aiThinking: "Sage думает…", aiImproving: "Sage улучшает текст…",
            aiContinuing: "Sage продолжает…", aiSummarizing: "Sage подводит итог…",
            aiApplied: "Применено", aiFailed: "Не удалось получить ответ",
            newNote: "Создать заметку",
            openFolder: "Открыть папку",
            emptyVaultTitle: "Заметок пока нет",
            emptyVaultBody: "В этой папке нет .md файлов. Создайте первую заметку или откройте другую папку с заметками.",
            newNoteName: "Заметка",
            noSelectionTitle: "Заметка не выбрана",
            noSelectionBody: "Выберите заметку в списке слева или создайте новую.",
            newFolder: "Новая папка",
            rename: "Переименовать",
            open: "Открыть",
            deleteFolder: "Удалить папку",
            sortBy: "Сортировка", sortByName: "По имени", sortByModified: "По дате изменения",
            copyPath: "Скопировать путь", copied: "Скопировано",
            ready: "готово"
        ),
        chat: Chat(
            title: "Чат с Sage",
            placeholder: "Спросите что-нибудь о ваших заметках…",
            perm: "Запрос доступа к микрофону…",
            transcribing: "Распознавание речи…",
            errorMsg: "Не удалось получить ответ от модели. Возможно, не хватает памяти.",
            retry: "Повторить",
            stopGen: "Остановить",
            voiceTitle: "Слушаю…",
            voiceHint: "Говорите — Whisper распознаёт речь локально",
            voiceCancel: "отменить",
            voiceConfirm: "остановить и распознать",
            history: "История",
            historyHeader: "История чатов · привязана к файлам и папкам",
            ctxVault: "Всё хранилище",
            ctxSelection: "Выделенный текст",
            clearChat: "Очистить чат",
            deletePrompt: "Удалить эту заметку?",
            deleted: "Удалено в Корзину",
            askTitle: "Спросите Sage",
            askBody: "Отвечает по вашим заметкам — полностью офлайн. Контекстом может быть файл или целая папка.",
            copy: "Копировать",
            suggest1: "Кратко о чём это",
            suggest2: "Выдели главное",
            suggest3: "Задай вопросы по содержимому",
            histToday: "Сегодня", histYesterday: "Вчера", histEarlier: "Ранее",
            histEmptyTitle: "Пока нет истории",
            histEmptyBody: "Разговоры с Sage сохраняются здесь и привязываются к файлу или папке, по которым вы спрашивали."
        ),
        search: Search(
            placeholder: "Поиск по всем заметкам…",
            noResults: "Ничего не найдено",
            askSub: "Задать вопрос локальному ИИ по всем заметкам",
            searching: "Поиск…",
            recent: "Недавние",
            results: "Результаты",
            askPrefix: "Спросить Sage"
        ),
        settings: Settings(
            title: "Настройки", general: "Основные", ai: "ИИ-модель", appearance: "Оформление",
            git: "Git-синхронизация", about: "О программе",
            generalSub: "Язык, хранилище и поведение приложения",
            language: "Язык интерфейса", languageSub: "Русский, English или 中文",
            vault: "Папка с заметками", change: "Изменить",
            startup: "Запуск при входе", startupSub: "Открывать Sage при старте macOS",
            spellcheck: "Проверка орфографии", spellcheckSub: "Подчёркивать ошибки в тексте",
            aiSub: "Управление локальными моделями и поведением ИИ",
            llmSection: "Модель ответов и саммари · LLM",
            whisperSection: "Распознавание речи · Whisper", download: "Скачать",
            appearanceSub: "Тема и акцентный цвет",
            theme: "Тема", accent: "Акцентный цвет", accentSub: "Цвет выделения и кнопок",
            gitSub: "Синхронизируйте заметки через Git-репозиторий",
            gitConnectTitle: "Подключите Git",
            gitConnectSub: "Версионируйте и синхронизируйте заметки через GitHub, GitLab или собственный сервер.",
            gitConnect: "Подключить репозиторий",
            branch: "Ветка", lastSync: "синхр.", synced: "Синхронизировано", disconnect: "Отключить",
            gitTokenHint: "HTTPS-токен (Personal Access Token)",
            autoSync: "Авто-синхронизация", autoSyncSub: "Коммитить и пушить изменения автоматически",
            syncFrequency: "Частота синхронизации",
            syncFrequencySub: "Как часто отправлять изменения в репозиторий",
            freqOnChange: "При изменении", freqEvery5: "5 мин", freqHourly: "Час", freqManual: "Вручную",
            recentCommits: "Последние коммиты", syncNow: "Синхронизировать сейчас", syncing: "Синхронизация…",
            version: "Версия",
            chipLocal: "100% локально", chipSilicon: "Apple Silicon", chipMarkdown: "Markdown",
            updates: "Обновления", updatesSub: "Sage обновляется автоматически в фоне",
            upToDate: "Актуально", checkingUpdates: "Проверка обновлений…", installingUpdate: "Установка…",
            checkUpdates: "Проверять обновления", checkNow: "Проверить сейчас", lastChecked: "Последняя проверка",
            updateAvailable: "Доступна версия", updateNow: "Обновить",
            downloadingUpdate: "Загрузка", updateReady: "готово к установке", restartNow: "Перезапустить",
            updateFailed: "Не удалось загрузить", retryUpdate: "Повторить",
            autoUpdate: "Автоматически обновлять", autoUpdateSub: "Скачивать и устанавливать обновления в фоне",
            youHaveVersion: "у вас",
            updateReadyTitle: "Обновление готово", updateAvailableTitle: "Доступно обновление", openAction: "Открыть",
            updateErrNetwork: "Не удалось связаться с сервером обновлений",
            updateErrChecksum: "Контрольная сумма не совпала",
            updateErrNoApp: "В архиве нет приложения",
            updateErrInstall: "Не удалось установить обновление",
            downloadIncomplete: "Загрузка не завершилась"
        ),
        theme: Theme(dark: "Тёмная", light: "Светлая", auto: "Авто"),
        tray: Tray(
            statusRunning: "работает локально", newChat: "Новый чат",
            search: "Поиск", settings: "Настройки", quit: "Выйти из Sage"
        ),
        menu: Menu( edit: "Правка", goMenu: "Переход", find: "Найти…", toggleSidebar: "Боковая панель",
            settings: "Настройки…",
            editorView: "Редактор", chatView: "Чат с Sage", settingsView: "Настройки", cycleTheme: "Сменить тему",
            aiMenu: "ИИ", askSage: "Спросить Sage…"
        ),
        models: Models(
            descSmall: "Лёгкая: быстро на любом Mac",
            descMid: "Умная, сильна в коде и многоязычности",
            descLarge: "Максимальное качество, нужен мощный Mac", ramSmall: "6 ГБ RAM", ramMid: "8 ГБ RAM", ramLarge: "16 ГБ RAM",
            whisperBaseDesc: "Оптимальный баланс скорости и точности",
            whisperSmallDesc: "Выше точность, медленнее",
            whisperTinyDesc: "Самая быстрая, базовая точность",
            whisperTurboDesc: "Высокая точность, ускоренная",
            whisperNone: "Без голосового ввода",
            whisperNoneDesc: "Можно включить позже в настройках",
            notInstalled: "не загружена", active: "активна", installed: "загружена",
            downloadingStatus: "Скачивание…"
        ),
        slash: Slash(
            aiAsk: "Спросить Sage…",
            linkURL: "Ссылка (URL)", linkNote: "Заметка (.md)", linkText: "Текст",
            linkAdd: "Добавить", linkCreate: "Создать заметку",
            blkText: "Текст", blkH1: "Заголовок 1", blkH2: "Заголовок 2", blkH3: "Заголовок 3",
            blkBullet: "Список", blkNumbered: "Нумерованный", blkCheck: "Чек-лист",
            blkQuote: "Цитата", blkTable: "Таблица", blkCode: "Код", blkDivider: "Разделитель",
            blkLink: "Ссылка", tableColumn: "Колонка"),
        toast: Toast(
            folderOpened: "Папка открыта",
            aiReplied: "Sage ответил в"),
        git: Git(
            commitAutoSync: "автосинхронизация", commitMerge: "слияние с remote",
            syncUpToDate: "Актуально", syncPushed: "Отправлено", syncConflict: "Конфликт",
            syncNoRepo: "Репозиторий не найден", syncUnrelated: "Несвязанные истории — переподключите репозиторий",
            connectConflict: "Конфликт при слиянии")
    )
}
