import Foundation

extension Strings {
    public static let zh = Strings(
        brandTagline: "本地 AI Markdown 编辑器",
        common: Common(
            back: "返回", cancel: "取消", delete: "删除", change: "更改", justNow: "刚刚"),
        ob: Onboarding(
            langTitle: "欢迎使用 Sage",
            langSub: "您的私人 AI 笔记编辑器。请选择语言。",
            stepFolder: "第 2 步，共 5 步",
            folderTitle: "您的笔记在哪里？",
            folderSub: "选择一个含 .md 文件的文件夹。Sage 会像 Obsidian 一样直接读写。",
            chooseFolder: "选择文件夹",
            folderHint: "任意含 Markdown 文件的文件夹",
            folderPicked: "已选择文件夹",
            privacyNote: "笔记保留在您的 Mac 上，Sage 不会上传任何内容到云端。",
            stepModel: "第 3 步，共 5 步",
            modelTitle: "选择 AI 模型",
            modelSub: "模型将下载并在本地运行，随时可更换。",
            recommended: "推荐",
            stepWhisper: "第 4 步，共 5 步",
            whisperTitle: "语音转文字",
            whisperSub: "选择 Whisper 模型用于语音输入，同样在本地运行。可跳过。",
            stepDownload: "第 5 步，共 5 步",
            downloading: "正在下载模型…",
            verifying: "正在校验完整性…",
            dlDone: "模型已就绪",
            dlErrorMsg: "无法下载模型。请检查网络后重试。",
            retry: "重试下载",
            readyTitle: "全部就绪！",
            readySub: "Sage 已配置完成，完全离线运行。",
            continueAction: "继续",
            openSage: "打开 Sage",
            stageModel: "第 1 步，共 2 步 · 回答模型",
            stageWhisper: "第 2 步，共 2 步 · 语音识别 (Whisper)",
            stageOnlyModel: "仅回答模型",
            downloadContinue: "下载并继续",
            speedUnit: "MB/秒"
        ),
        nav: Nav(search: "搜索", editor: "编辑器", chat: "与 Sage 对话"),
        app: App(
            files: "文件", localRunning: "本地运行", cloudRunning: "DeepSeek 云端",
            outline: "大纲", info: "信息", words: "字数", edited: "修改",
            askInline: "让 Sage 处理这段文字",
            whatsNewTitle: "Sage 新变化", whatsNewOk: "知道了", revealInFinder: "在访达中显示",
            aiThinking: "Sage 正在思考…", aiImproving: "Sage 正在润色…",
            aiContinuing: "Sage 正在续写…", aiSummarizing: "Sage 正在总结…",
            aiApplied: "已应用", aiFailed: "未能获得模型响应",
            newNote: "新建笔记",
            openFolder: "打开文件夹",
            emptyVaultTitle: "暂无笔记",
            emptyVaultBody: "此文件夹中没有 .md 文件。请创建第一篇笔记，或打开另一个含笔记的文件夹。",
            newNoteName: "笔记",
            noSelectionTitle: "未选择笔记",
            noSelectionBody: "请从左侧列表中选择一篇笔记，或新建一篇。",
            newFolder: "新建文件夹",
            rename: "重命名",
            open: "打开",
            deleteFolder: "删除文件夹",
            sortBy: "排序", sortByName: "按名称", sortByModified: "按修改日期",
            copyPath: "复制路径", copied: "已复制",
            ready: "完成"
        ),
        chat: Chat(
            title: "与 Sage 对话",
            placeholder: "询问关于笔记的任何问题…",
            perm: "正在请求麦克风权限…",
            transcribing: "正在识别语音…",
            errorMsg: "无法从模型获取回复，可能是内存不足。",
            retry: "重试",
            stopGen: "停止",
            voiceTitle: "正在聆听…",
            voiceHint: "请讲话 — Whisper 在本地识别",
            voiceCancel: "取消",
            voiceConfirm: "停止并识别",
            history: "历史记录",
            historyHeader: "对话历史 · 按文件和文件夹关联",
            ctxVault: "整个笔记库",
            ctxSelection: "选中的文字",
            clearChat: "清空对话",
            deletePrompt: "删除这条笔记？",
            deleted: "已移到废纸篓",
            askTitle: "问问 Sage",
            askBody: "根据你的笔记作答 — 完全离线。上下文可以是文件或整个文件夹。",
            copy: "复制",
            suggest1: "简要说说这是什么",
            suggest2: "提炼要点",
            suggest3: "就内容提出问题",
            histToday: "今天", histYesterday: "昨天", histEarlier: "更早",
            histEmptyTitle: "暂无历史",
            histEmptyBody: "与 Sage 的对话保存在这里，并关联到你所询问的文件或文件夹。"
        ),
        search: Search(
            placeholder: "搜索所有笔记…",
            noResults: "无结果",
            askSub: "让本地 AI 检索全部笔记",
            searching: "搜索中…",
            recent: "最近",
            results: "结果",
            askPrefix: "询问 Sage"
        ),
        settings: Settings(
            title: "设置", general: "通用", ai: "AI 模型", appearance: "外观",
            git: "Git 同步", about: "关于",
            generalSub: "语言、库与应用行为",
            language: "界面语言", languageSub: "Русский、English 或 中文",
            vault: "笔记文件夹", change: "更改",
            startup: "登录时启动", startupSub: "macOS 启动时打开 Sage",
            spellcheck: "拼写检查", spellcheckSub: "标出文中错误",
            aiSub: "管理本地模型与 AI 行为",
            llmSection: "回答与摘要模型 · LLM",
            whisperSection: "语音识别 · Whisper", download: "下载",
            appearanceSub: "主题与强调色",
            theme: "主题", accent: "强调色", accentSub: "高亮与按钮颜色",
            gitSub: "通过 Git 仓库同步笔记",
            gitConnectTitle: "连接 Git",
            gitConnectSub: "通过 GitHub、GitLab 或自有服务器版本化并同步笔记。",
            gitConnect: "连接仓库",
            branch: "分支", lastSync: "同步", synced: "已同步", disconnect: "断开连接",
            gitTokenHint: "HTTPS 令牌 (Personal Access Token)",
            autoSync: "自动同步", autoSyncSub: "自动提交并推送更改",
            syncFrequency: "同步频率",
            syncFrequencySub: "向仓库推送更改的频率",
            freqOnChange: "更改时", freqEvery5: "5 分钟", freqHourly: "小时", freqManual: "手动",
            recentCommits: "最近提交", syncNow: "立即同步", syncing: "同步中…",
            version: "版本",
            chipLocal: "100% 本地", chipSilicon: "Apple Silicon", chipMarkdown: "Markdown",
            updates: "更新", updatesSub: "Sage 在后台自动更新",
            upToDate: "已是最新", checkingUpdates: "正在检查更新…", installingUpdate: "正在安装…",
            checkUpdates: "检查更新", checkNow: "立即检查", lastChecked: "上次检查",
            updateAvailable: "可用版本", updateNow: "更新",
            downloadingUpdate: "正在下载", updateReady: "准备安装", restartNow: "重新启动",
            updateFailed: "下载更新失败", retryUpdate: "重试",
            autoUpdate: "自动更新", autoUpdateSub: "在后台下载并安装更新",
            youHaveVersion: "当前",
            updateReadyTitle: "更新已就绪", updateAvailableTitle: "有可用更新", openAction: "打开",
            updateErrNetwork: "无法连接更新服务器",
            updateErrChecksum: "校验和不匹配",
            updateErrNoApp: "压缩包中没有应用",
            updateErrInstall: "无法安装更新",
            downloadIncomplete: "下载未完成",
            deepseekSection: "DeepSeek API",
            deepseekSub: "使用云端模型替代本地模型。出错时由本地模型回答。",
            deepseekPlaceholder: "API 密钥 (sk-…)",
            deepseekCheck: "验证并保存",
            deepseekConnected: "已连接",
            deepseekModelLabel: "模型",
            deepseekDelete: "删除",
            deepseekInvalid: "密钥无效"
        ),
        theme: Theme(dark: "深色", light: "浅色", auto: "自动"),
        tray: Tray(
            statusRunning: "本地运行", newChat: "新对话",
            search: "搜索", settings: "设置", quit: "退出 Sage"
        ),
        menu: Menu( edit: "编辑", goMenu: "前往", find: "查找…", toggleSidebar: "侧边栏",
            settings: "设置…",
            editorView: "编辑器", chatView: "与 Sage 对话", settingsView: "设置", cycleTheme: "切换主题",
            aiMenu: "AI", askSage: "询问 Sage…"
        ),
        models: Models(
            descSmall: "轻量：任何 Mac 都流畅",
            descMid: "聪明，擅长代码与多语言",
            descLarge: "极致质量，需要强劲的 Mac", ramSmall: "6 GB 内存", ramMid: "8 GB 内存", ramLarge: "16 GB 内存",
            whisperBaseDesc: "速度与精度的最佳平衡",
            whisperSmallDesc: "精度更高，速度较慢",
            whisperTinyDesc: "最快，精度基础",
            whisperTurboDesc: "高精度，加速版",
            whisperNone: "不使用语音输入",
            whisperNoneDesc: "可稍后在设置中开启",
            notInstalled: "未下载", active: "使用中", installed: "已下载",
            downloadingStatus: "下载中…",
            groupLight: "轻量 · 任何 Mac 都快", groupStandard: "标准 · 速度与质量平衡", groupMax: "旗舰 · 最高质量（16 GB+）"
        ),
        slash: Slash(
            aiAsk: "询问 Sage…",
            linkURL: "链接 (URL)", linkNote: "笔记 (.md)", linkText: "文本",
            linkAdd: "添加", linkCreate: "新建笔记",
            blkText: "文本", blkH1: "标题 1", blkH2: "标题 2", blkH3: "标题 3",
            blkBullet: "项目符号列表", blkNumbered: "编号列表", blkCheck: "待办列表",
            blkQuote: "引用", blkTable: "表格", blkCode: "代码", blkDivider: "分隔线",
            blkLink: "链接", tableColumn: "列"),
        toast: Toast(
            folderOpened: "文件夹已打开",
            aiReplied: "Sage 已在以下位置回复"),
        git: Git(
            commitAutoSync: "自动同步", commitMerge: "合并远程",
            syncUpToDate: "已是最新", syncPushed: "已推送", syncConflict: "冲突",
            syncNoRepo: "未找到仓库", syncUnrelated: "历史不相关 — 请重新连接仓库",
            connectConflict: "合并冲突")
    )
}
